### ISSUE TITLE
Nusantara for Redmi note 11 screenshot issue

### ISSUE THREAD

**Issue by PrashunPareek** [NusantaraProject-ROM/Nusantara#1]
Whenever I take screenshot while playing music and easphones plugged in, the audio outputs from speaker rather earphones.

**Comment by ianjya** [comment]
> Whenever I take screenshot while playing music and easphones plugged in, the audio outputs from speaker rather earphones.

wait, how can you custom a redmi note 11 cellphone while the device listed on the redmi note 11 website doesn't exist..

**Comment by ianjya** [comment]
> Whenever I take screenshot while playing music and easphones plugged in, the audio outputs from speaker rather earphones.

Which android version did you install, 12 or 13?

**Comment by PrashunPareek** [comment]
12 and It is resolved in further updates.
